nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: true
        forced_allow_origin_value: ~
